import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Swords } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Team={name:string;slug:string;logo_url:string|null};
type RawMatch={id:string;map_name:string|null;stage:string|null;date:string|null;team1_score:number|null;team2_score:number|null;source:string|null;verified:boolean|null;team1:Team|Team[]|null;team2:Team|Team[]|null;winner:Team|Team[]|null};
type Match=Omit<RawMatch,"team1"|"team2"|"winner">&{team1:Team|null;team2:Team|null;winner:Team|null};
type RawResult={match_id:string;team_id:string;placement:number|null;kills:number|null;total_points:number|null;team:Team|Team[]|null};
type Result=Omit<RawResult,"team">&{team:Team|null};
const PAGE_SIZE=10;
function one<T>(value:T|T[]|null){return Array.isArray(value)?value[0]||null:value;}
function pageNumber(value?:string){const page=Number.parseInt(value||"1",10);return Number.isFinite(page)&&page>0?page:1;}
function formatDate(value:string|null){return value?new Date(value).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"TBD";}
function initials(value:string){return value.split(" ").filter(Boolean).slice(0,2).map((part)=>part[0]).join("").toUpperCase();}
function TeamMark({team}:{team:Team|null}){const name=team?.name||"TBD";return <div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden border border-white/15 bg-white/[0.035]">{team?.logo_url?<Image src={team.logo_url} alt={`${name} logo`} width={48} height={48} className="h-full w-full object-contain p-1.5"/>:<span className="text-[10px] font-black text-white/45">{initials(name)}</span>}</div>;}

export default async function MatchesPage({searchParams}:{searchParams?:Promise<{page?:string}>}){
  const params=searchParams?await searchParams:{};const page=pageNumber(params.page),offset=(page-1)*PAGE_SIZE;
  const {data,error,count}=await supabase.from("matches").select("id,map_name,stage,date,team1_score,team2_score,source,verified,team1:team1_id(name,slug,logo_url),team2:team2_id(name,slug,logo_url),winner:winner_team_id(name,slug,logo_url)",{count:"exact"}).order("date",{ascending:false}).range(offset,offset+PAGE_SIZE-1);
  if(error)return <main className="pr-container py-20"><p className="pr-kicker">Data unavailable</p><h1 className="mt-4 text-5xl font-semibold text-white">Matches could not be loaded.</h1></main>;
  const matches=((data||[]) as RawMatch[]).map((match)=>({...match,team1:one(match.team1),team2:one(match.team2),winner:one(match.winner)})) as Match[];
  const ids=matches.map((match)=>match.id);const resultQuery=ids.length?await supabase.from("team_match_results").select("match_id,team_id,placement,kills,total_points,team:team_id(name,slug,logo_url)").in("match_id",ids):{data:[],error:null};
  const results=((resultQuery.data||[]) as RawResult[]).map((row)=>({...row,team:one(row.team)})) as Result[];const byMatch=new Map<string,Result[]>();for(const row of results){const list=byMatch.get(row.match_id)||[];list.push(row);byMatch.set(row.match_id,list);}
  const total=count||0,pages=Math.max(1,Math.ceil(total/PAGE_SIZE)),verified=matches.filter((match)=>match.verified).length;
  return <main className="bg-[var(--pr-bg)] text-white">
    <section className="border-b border-white/15"><div className="pr-container grid gap-12 py-16 md:py-24 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="pr-kicker">Results · maps · competitive history</p><h1 className="mt-5 text-[clamp(4.5rem,9vw,9rem)] font-semibold uppercase leading-[.78] tracking-[-.08em]">Match<br/><span className="text-[var(--pr-red)]">reports.</span></h1></div><div className="lg:pb-2"><p className="max-w-xl text-base leading-7 text-white/50">Follow head-to-head scores and battle-royale standings through promoted, traceable competitive records.</p><div className="mt-7"><Link href="/tournaments" className="pr-button pr-button-primary text-[10px]">Explore tournaments</Link></div></div></div></section>
    <section className="border-b border-white/15"><div className="pr-container grid grid-cols-3">{[[total,"Match records"],[verified,"Verified on page"],[10,"Matches per page"]].map(([value,label])=><div key={label} className="border-r border-white/15 px-5 py-7 first:border-l md:px-8"><p className="text-2xl font-semibold">{value}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[.16em] text-white/28">{label}</p></div>)}</div></section>
    <section className="pr-container py-16 md:py-22"><div className="flex items-end justify-between border-b border-white/15 pb-7"><div><p className="pr-kicker">Match centre · page {page}</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] md:text-6xl">Latest records.</h2></div><Swords size={20} className="text-[var(--pr-red)]"/></div><div>{matches.length?matches.map((match)=>{const rows=(byMatch.get(match.id)||[]).sort((a,b)=>(a.placement||999)-(b.placement||999));const h2h=Boolean(match.team1||match.team2);const winner=match.winner?.name||rows.find((row)=>row.placement===1)?.team?.name||"Pending";return <Link key={match.id} href={`/match/${match.id}`} className="pr-ranking-row group grid gap-5 border-b border-white/10 py-6 lg:grid-cols-[150px_1fr_180px_22px] lg:items-center"><div><p className="text-sm font-semibold">{formatDate(match.date)}</p><p className="mt-2 text-[9px] font-bold uppercase tracking-[.15em] text-white/25">{match.stage||"Match"} · {match.map_name||"Map TBD"}</p></div>{h2h?<div className="grid grid-cols-[1fr_auto_1fr] items-center gap-4"><Side team={match.team1}/><p className="text-3xl font-semibold tracking-[-.06em]"><span>{match.team1_score||0}</span><span className="px-3 text-white/20">:</span><span>{match.team2_score||0}</span></p><Side team={match.team2} right/></div>:<div className="flex items-center gap-5"><TeamMark team={rows[0]?.team||null}/><div><p className="font-semibold">{rows[0]?.team?.name||"Battle royale field"}</p><p className="mt-1 text-[9px] uppercase tracking-[.14em] text-white/25">{rows.length} team results · {rows.reduce((sum,row)=>sum+(row.kills||0),0)} kills</p></div></div>}<div className="lg:text-right"><p className="text-[9px] uppercase tracking-[.14em] text-white/25">Winner</p><p className="mt-2 truncate font-semibold text-[var(--pr-gold)]">{winner}</p></div><ArrowRight size={15} className="hidden text-white/20 group-hover:text-[var(--pr-red)] lg:block"/></Link>}):<p className="py-14 text-white/35">No matches found on this page.</p>}</div><nav className="mt-8 flex items-center justify-between border-t border-white/15 pt-7"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-white/30">Page {Math.min(page,pages)} of {pages}</p><div className="flex gap-2">{page>1?<Link href={`/matches?page=${page-1}`} className="pr-button pr-button-secondary text-[10px]">Previous 10</Link>:null}{page<pages?<Link href={`/matches?page=${page+1}`} className="pr-button pr-button-primary text-[10px]">Next 10 <ArrowRight size={13}/></Link>:null}</div></nav></section>
  </main>;
}
function Side({team,right=false}:{team:Team|null;right?:boolean}){return <div className={`flex min-w-0 items-center gap-3 ${right?"flex-row-reverse text-right":""}`}><TeamMark team={team}/><p className="truncate font-semibold">{team?.name||"TBD"}</p></div>;}
